version: '3.8'

services:
  bot:
    build:
      context: .
    command: bot/entrypoint.sh
    env_file: .env


  db:
    image: postgres:16.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5335:5432"


  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
